[tool.poetry]
name = "func-locator"
version = "0.1.0"
description = ""
authors = ["oneshell <oneshell@mbp.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
r2pipe = "^1.8.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
